ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS bank_name TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS account_number TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS ifsc TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS upi_id TEXT;
