ALTER TABLE product_variants
  ADD COLUMN IF NOT EXISTS length_cm  NUMERIC(6,2) DEFAULT 10,
  ADD COLUMN IF NOT EXISTS breadth_cm NUMERIC(6,2) DEFAULT 10,
  ADD COLUMN IF NOT EXISTS height_cm  NUMERIC(6,2) DEFAULT 10;
